import { AnalysisResult, JobSkill } from "@/types";
import { priorityFor, Priority } from "@/lib/skills/engine";

const PRIORITY_LABEL: Record<Priority, string> = {
  critical: "Critical",
  important: "Important",
  recommended: "Recommended",
};

function pct(f: number): string {
  return `${Math.round(f * 100)}%`;
}

function skillLine(s: JobSkill): string {
  const req = s.isRequired ? " · required" : "";
  return `- **${s.name}** — ${pct(s.frequency)} of postings${req}`;
}

/**
 * Render an analysis as a shareable Markdown report. A recruiter or program director
 * can drop this straight into a doc — it's a proper deliverable, not a raw JSON dump.
 */
export function toMarkdownReport(result: AnalysisResult): string {
  const lines: string[] = [];
  const mode = result.meta?.mode === "live" ? "live job data" : "sample job data";

  lines.push(`# Curriculum Gap Analysis`);
  lines.push("");
  lines.push(
    `Analyzed against **${result.totalJobsAnalyzed} job postings** (${mode}).`,
  );
  lines.push("");
  lines.push(`## Summary`);
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Coverage score | **${Math.round(result.coverageScore)}%** |`);
  lines.push(`| Skills covered | ${result.coveredSkills.length} |`);
  lines.push(`| Skills missing | ${result.missingSkills.length} |`);
  lines.push(`| Curriculum-only (bonus) | ${result.bonusSkills.length} |`);
  lines.push("");

  // Prioritized roadmap
  lines.push(`## Learning roadmap (highest-impact gaps first)`);
  lines.push("");
  const tiers: Priority[] = ["critical", "important", "recommended"];
  for (const tier of tiers) {
    const inTier = result.missingSkills.filter((s) => priorityFor(s) === tier);
    if (inTier.length === 0) continue;
    lines.push(`### ${PRIORITY_LABEL[tier]}`);
    lines.push("");
    for (const s of inTier) lines.push(skillLine(s));
    lines.push("");
  }
  if (result.missingSkills.length === 0) {
    lines.push(`No gaps found — the curriculum covers every in-demand skill.`);
    lines.push("");
  }

  // Covered strengths
  lines.push(`## Covered strengths`);
  lines.push("");
  if (result.coveredSkills.length === 0) {
    lines.push(`_No overlap with the analyzed postings._`);
  } else {
    for (const s of result.coveredSkills.slice(0, 15)) lines.push(skillLine(s));
  }
  lines.push("");

  // Recommendations
  lines.push(`## Recommendations`);
  lines.push("");
  result.recommendations.forEach((rec, i) => lines.push(`${i + 1}. ${rec}`));
  lines.push("");

  lines.push(`---`);
  lines.push(`_Generated by the Curriculum Gap Analyzer._`);

  return lines.join("\n");
}
